op: AND
sub_filters {
  name: "corrected_demo.age.min_age"
  op: EQUAL
  value: "18"
}
sub_filters {
  name: "corrected_demo.age.max_age"
  op: EQUAL
  value: "24"
}
sub_filters {
  name: "corrected_demo.gender"
  op: EQUAL
  value: "GENDER_FEMALE"
}

