name: "gb_gb_male_25_34_full_adf"
identifier_type_filters { op: TRUE }
identifier_type_names: "full_adf"
dirac_mixture {
  alphas: 0.5
  alphas: 0.5
  deltas { coordinates: 1.2 }
  deltas { coordinates: 0.8 }
}

