name: "us_us_female_35_99_full_adf"
identifier_type_filters { op: TRUE }
identifier_type_names: "full_adf"
dirac_mixture {
  alphas: 0.2
  alphas: 0.8
  deltas { coordinates: 1.0 }
  deltas { coordinates: 1.0 }
}

