name: "us_us_male_18_24_full_adf"
identifier_type_filters { op: TRUE }
identifier_type_names: "full_adf"
dirac_mixture {
  alphas: 0.1
  alphas: 0.9
  deltas { coordinates: 2.8 }
  deltas { coordinates: 0.8 }
}

