# Copyright 2022 The Cross-Media Measurement Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Integration tests for model compiler

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, edited]
  workflow_dispatch:

jobs:
  model-compiler-integration-tests:
    name: Integration tests for model compiler
    runs-on: ubuntu-18.04
    env:
      COMPILER_WORK_DIR: ${{ github.workspace }}/tmp/model_compiler_integration_tests
    steps:
      - name: Check out revision
        uses: actions/checkout@v2

      - name: Create temporary directory and copy input data
        shell: bash
        run: |
          mkdir -p ${{ env.COMPILER_WORK_DIR }}
          cp ${{ github.workspace }}/src/test/textproto/integration_tests_data/* ${{ env.COMPILER_WORK_DIR }}

      - name: Bazel build model compiler
        shell: bash
        run: bazel build -c opt //src/main/cc/wfa/virtual_people/training/model_compiler:compiler_main

      - name: Run model compiler
        shell: bash
        run: |
          cd ${{ env.COMPILER_WORK_DIR }}
          ${{ github.workspace }}/bazel-bin/src/main/cc/wfa/virtual_people/training/model_compiler/compiler_main --input_path=root_node_config.textproto --output_path=compiled_model.textproto
          cd ${{ github.workspace }}
